# This is our GitHub Actions workflow file

name: build applications #App workflow


runs: #jobs:
  using: composite
  # build:

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # Removed the commented-out clone line, as `actions/checkout` already handles repository checkout

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.0'
        cache : 'pip'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Install Poetry
      uses: snok/install-poetry@v1

    # Uncomment the following if you want to run linting with flake8
    - name: Lint with flake8
      run: poetry run make check
      shell: bash

    # - name: Install Poetry
    #   run: |
    #     curl -sSL https://install.python-poetry.org | python3 -  # Fixed the command
    #     echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV  # Correctly exports to the environment

    # - name: Install dependencies using Poetry
    #   run: poetry install  # Fixed the Poetry command

