# This is our GitHub Actions workflow file

name: Lint workflow

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

permissions:
  contents: read

jobs:
  lint: # build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: build applications
        uses: ./.github/actions/build-application

      - name: Lint with flake8
        run: poetry run make check

      # - name: Install Poetry
      #   run: |
      #     curl -sSL https://install.python-poetry.org | python3 -  # Fixed the command
      #     echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV  # Correctly exports to the environment

      # - name: Install dependencies using Poetry
      #   run: poetry install  # Fixed the Poetry command

